AWSTemplateFormatVersion: "2010-09-09"
Description: Create S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "my-demo-bucket-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Имя созданного бакета
    Value: !Ref MyS3Bucket
